### ISSUE TITLE
Credential download missing some users

### ISSUE THREAD

**Issue by ejimba** [medic/cht-user-management#104]
Instance: Nyandarua Live

User creation succeeded (user creation failed silently - contact was created but user account was not) but download missing username and password.

Not sure if its just timeout or a deeper issue.

<img width="715" alt="Screenshot 2024-03-18 at 11 17 22 AM" src="https://github.com/medic/cht-user-management/assets/5405838/8c94b851-c497-44be-9ecd-719df40d6605">

**Comment by kennsippell** [comment]
@ejimba Would you kindly check to see if there were any failures during user creation? You can see that here.  

![image](https://github.com/medic/cht-user-management/assets/9014751/6231b39c-f1f5-43a3-b565-cc7f8469be71)

Occasionally, there are networking related failures which can cause this sort of failure.  We recently made improvements to the retry logic (#17) to improve this...  but this broke and we're fixing that again (#103).  We will have that working again in a few days. 

I encourage you to check for failures before exporting credentials.  If you see a failure, can retry it by clicking this button. It will resume from the point of the failure (it won't create a duplicate contact).

![image](https://github.com/medic/cht-user-management/assets/9014751/df44a824-6caa-424f-aedb-6050accd9eae)

**Comment by ejimba** [comment]
Unfortunately I have already cleared the session. Will be on the lookout. And will report on any developments.
Thanks. We can close this for now
