### ISSUE TITLE
Use the new /api/v2/users endpoints in cht-core 4.7

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-user-management#114]
Issue https://github.com/medic/cht-core/issues/8877 with PR https://github.com/medic/cht-core/pull/8928 includes new /api/v2/users endpoints.

1. Searching for a user by facility_id
2. Looking up the details of a single username

The information in the `users` database is more secure (https://github.com/medic/cht-core/issues/8886), so updating to these endpoints is important.

Let's start with a quick prototype and give feedback to the core team, then actually support the new endpoints when working with a CHT endpoint that is >=4.7.

**Comment by mrjones-plip** [comment]
If it will help, I have deployed the latest `8877-lookup-single-user` branch to EKS so there's a central, always online version to test against.  If you need the login, it's `medic` and the password is in `1password` under `mrjones.dev.medicmobile.org`.   

Instance is at https://mrjones.dev.medicmobile.org/

You're welcome to use this for the coming few weeks, no problem. Push any config, delete any data, do anything you want!  As well, I'm happy to reset it to a clean install if needed - lemme know!

**Comment by mrjones-plip** [comment]
Yay - Great to see this API in use - thanks Kenn!
