### ISSUE TITLE
Support the multiple DoB formats used by sample UG inputs

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-user-management#119]
> * There are hundreds of values in the format `13/2/1985` and hundreds in the format `1977-08-14`. Currently we only support the latter. Should we support both?

 _Originally posted by @kennsippell in [#38](https://github.com/medic/cht-user-management/issues/38#issuecomment-2018097793)_

**Comment by jonathanbataire** [comment]
Kenn this would cause a nightmare dealing with data in psql lets stick to yyyy-mm-dd

**Comment by jonathanbataire** [comment]
ignore if in the json it shows up as yyyy-mm-dd and this is just for the ui and template :)

**Comment by kennsippell** [comment]
@jonathanbataire This is the accepted `input` for DoB, but the `output` will always be in ISO format `yyyy-mm-dd`.
