### ISSUE TITLE
Cloud-Based execution of move-contacts commands

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-user-management#12]
Currently this tool outputs a `cht` console line which can be executed to move contacts.  Let's take this to the next step and execute that command in the cloud.

**Comment by kennsippell** [comment]
Discussion here to also move households and not just CHP areas https://github.com/moh-kenya/config-echis-2.0/issues/1662

**Comment by paulpascal** [comment]
> Discussion here to also move households and not just CHP areas https://github.com/moh-kenya/config-echis-2.0/issues/1662 + using forms in the CHT to trigger the move (not a UI interface like cht-user-management).

Please @kennsippell, sorry for coming back on this but the issue link you shared could not be found. (404).
This is something the MoH Togo is requesting... and I am really interested in this feature.

thanks

**Comment by kennsippell** [comment]
Notes from design conversation today with @paulpascal.

What states will jobs go through:

1. Pending (waiting)
2. (Not MVP) Flag user for maintenance
3. (Not MVP) Wait for the user to sync
4. (Not MVP) Check sentinel backlog and couch2pg backlog to ensure it is safe
5. Execute the move-contacts + upload-docs
6. Success
7. Fail

What is needed from a Cloud-Based Queue

1. Hostable in docker (rabbitMQ)? Or can it be cloud-based like SQS?
2. Great if had a UI to view status, click to cancel, click to view logs, etc so we don’t have to build that
3. We need to wait for users to sync... so we need to able to pop from queue many times, but decide not to process job for some days

Design questions:

1. What should happen if a user never syncs? Should we eventually move them? What is a reasonable limit?
2. What queuing technology should we use for this?
3. How can a user cancel a job? Learn about the state of the job? Investigate a failed job?

Next Steps:

1. Evaluation of cloud-based queues against requirements above. 
  1. Pick one.
  2. It’d be great to just write this down and kinda get some opinions. Maybe post it on #development or #cht-user-management
2. Pick how things will get pushed into the queue?
  * Options
    * User management tool push into queue
    * UI in CHT 
  * The biggest factor here is WHO should move contacts and reorganize hierarchies? Should they be online users? Who is it in #moh-togo/#moh-uganda/#moh_kenya?
3. Make work thread(s) that pull from the queue and kick of cht-conf move-contacts code (via process, or via import, whatever)

-- End of MVP --

4. Expose the queue’s UI somehow? 
5. Or build a UI to show status, cancel, etc.
6. Moving contacts safely - Don’t take the server down
7. Moving contacts safely - Don’t lose personal data

**Comment by mrjones-plip** [comment]
Any thoughts of doing this through a long lived task via CHT Core API and Sentinel?  While it would mean needing to upgrade Core where you want to use the feature, there's already a system in place for long running tasks and queues - eg [bulk upload](https://docs.communityhealthtoolkit.org/apps/guides/data/users-bulk-load/). The user man. tool should also be able to query the status of the job as well.

**Comment by kennsippell** [comment]
@mrjones-plip Who can we talk with to learn about how this is implemented in sentinel and how these long running tasks/queues work today? I'm only familiar with our homebrew couch-based queuing system used for outbound push. Is this the same system?

**Comment by mrjones-plip** [comment]
@latin-panda @m5r and @njuguna-n did the original work on the CSV bulk upload  according the [PR I found](https://github.com/medic/cht-core/pull/7678)! 

cc @jkuester

**Comment by kennsippell** [comment]
Thanks. Quick scan and this PR doesn't appear to touch sentinel at all. Perhaps bulk uploads aren't processed by sentinel at all?

**Comment by mrjones-plip** [comment]
Oh! Well, that would be good to know if it wasn't in Sentinel - sorry if I've led you astray.

I dug up some [test steps](https://medic.slack.com/archives/C02FMC810UE/p1691106221944959?thread_ts=1690986805.897179&cid=C02FMC810UE) (private slack link) that I originally used to performance testing of bulk upload.  Until some the engineers chime in on this ticket, maybe this will better expose how it works? From what I can tll there's a `parseCsv()` [function](https://github.com/medic/cht-core/blob/4ced6937a73b105fa2a970d729e3803afd29893a/shared-libs/user-management/src/users.js#L653) which writes to the `medic_log` database.  The `medic_log` entry is queried via AJAX to update the job progress on screen as it's rows of the CSV are processed. When it's done a CSV of errors is available for download.

**Comment by latin-panda** [comment]
Yes, as @mrjones-plip explained, that bulk upload tool is a bunch of promises and waits until all are resolved - ongoing in the server (not a scheduler and not sentinel) - and writes the upload status in the medic_log (how many users are pending, failed, or successful).
At the moment, I don't have more experience in Sentinel [than what's documented](https://docs.communityhealthtoolkit.org/core/overview/transitions/), perhaps if this feature is expected to be heavy, it might need to create some sort [of transition](https://docs.communityhealthtoolkit.org/apps/reference/app-settings/transitions/) ([entry point](https://github.com/medic/cht-core/blob/4ced6937a73b105fa2a970d729e3803afd29893a/sentinel/src/transitions.js#L23)) then Sentinel will [start listening](https://github.com/medic/cht-core/blob/4ced6937a73b105fa2a970d729e3803afd29893a/sentinel/src/lib/feed.js#L103) for db changes and queueing those transitions

**Comment by kennsippell** [comment]
OK good to know! Thanks to both of you.

If we consider the long-term plan to move contacts without dataloss via something like https://github.com/medic/cht-core/issues/8860, then this will become a very async operation (multiple days). Therefore, I don't think the pattern used for bulk upload is right for this problem.

I think it's quite a bit more complex to build in sentinel.  It would probably look a bit like how outbound push is written now; but I personally think we shouldn't be investing in our bespoke queuing technologies. If a Core Dev has time to take this on, I do think it would be a more reusable approach across projects ... but I also think this is too much to ask of @paulpascal who has time to make progress on this now, and is doing great via a public reusable queue.

Thanks for the suggestion and please do let me know if you think we're missing anything or if this is not what users need.

**Comment by mrjones-plip** [comment]
Thanks @kennsippell  - that sounds like a fair assessment! I appreciate the consideration on what it would look like inside CHT Core vs outside.
