### ISSUE TITLE
Support for the April 8th ICT and HRIO training in Kenya

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-user-management#132]
* Support @PhilipNgari with creation of training materials
* Create users on training or staging instances prior to the training

**Comment by PhilipNgari** [comment]
started off on a template [herein](https://docs.google.com/presentation/d/1PAeyqzid13o6lHREpxp_k3O1V_zpn1Bu/edit#slide=id.p12) cc @antonykhaemba  as discussed. cc @Mercyamulele

**Comment by antonykhaemba** [comment]
cc @esthermmoturi
