### ISSUE TITLE
Rename "Replace CHU" to "Replace CHA"

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-user-management#139]
> The label should be Replace Existing CHA. The confusion came in as they thought this would create a new CHU and then move CHP areas to the new CHU.
> Ideally we should only have the subcounty, chu and CHA Name/Phone

**Comment by kennsippell** [comment]
![image](https://github.com/medic/cht-user-management/assets/9014751/9e74ad4e-7072-4dbe-bbcf-1814f39bd82e)

Reactivating this since we are now getting different feedback.

**Comment by PhilipNgari** [comment]
weighing on this too as user managers have the same challenge.let us rename it to  "community health Assistant" as that's the expected action

additionally, the new CHP details section below outgoing CHP should have a label e.g Incoming CHP
