### ISSUE TITLE
Medic-hosted CIV User Management Tool 

### ISSUE THREAD

**Issue by inromualdo** [medic/cht-user-management#190]
Based on #110 

- [x] verify URL: https://users-chis-civ.app.medicmobile.org
- [x]  ensure repo has config for civ - see https://github.com/medic/cht-user-management/pull/189
- [x]  create DNS entry: `CNAME` of `users-chis-civ.app.medicmobile.org` -> `k8s-prodchtalb-dcc00345ac-1792311525.eu-west-2.elb.amazonaws.com`
- [x]  create helm values file in [correct location](https://github.com/medic/cht-user-management/tree/main/scripts/deploy/values)
- [x]  deploy helm chart so the instance is live at above URL

**Comment by inromualdo** [comment]
@kennsippell 
Could you assist us with the deployment?

I currently don't have the access to deploy, but I have submitted a ticket to request access.

**Comment by Marina-Kenf** [comment]
The following issue is blocking the creation of users for the go-live planned for August.
@Hareet I'd like to request this to be treated as a priority. Thank you!

**Comment by hiellavis** [comment]
Hi @medic/site-reliability-engineering ,
May we please have an update on this ? 
Thx

cc @henokgetachew @Marina-Kenf @inromualdo @loukmantidjani

**Comment by henokgetachew** [comment]
I'm putting this on my plate for next week.

**Comment by mrjones-plip** [comment]
Created `CNAME` for `users-moh-civ.app` to point to `k8s-prodchtalb-dcc00345ac-1792311525.eu-west-2.elb.amazonaws.com` on this AWS page:

![image](https://github.com/user-attachments/assets/a7b17e9d-f5cd-48f9-a5a2-799927b15bb9)

There's now 4 `users*.app` DNS entries:

![image](https://github.com/user-attachments/assets/6730cce6-195b-43ea-8c42-8714d3b77224)

**Comment by mrjones-plip** [comment]
Note that because we match config name <> URL, I change the URL to be `users-chis-civ.app` so that it matches the [config](https://github.com/medic/cht-user-management/tree/main/src/config/chis-civ) of `chis-civ`.  This matches the deployments for UG, KE, and TG

**Comment by mrjones-plip** [comment]
whew!  This took a bit of remembering how we deploy things. I've covered the steps in detail in a [pending PR](https://github.com/medic/cht-user-management/pull/197), but tl;dr:

0. make sure your [helm charts repo](https://github.com/medic/helm-charts) is up to date
1. make a new values YAML in `deploy` [branch](https://github.com/medic/cht-user-management/tree/deploy) for CIV
2. make sure the right version in the `tag:` [field](https://github.com/medic/cht-user-management/blob/deploy/scripts/deploy/values/users-chis-civ.yaml#L3) is in the values file. As of this writing it is `1.3.20`
3. check out the `deploy` branch 
4.  in the `scripts/deploy` directory and run the install command:
   ```
   helm install --kube-context arn:aws:eks:eu-west-2:720541322708:cluster/prod-cht-eks \
      --namespace users-chis-prod  \
      --values values/users-chis-civ.yaml users-chis-civ  \
      helm-charts/charts/cht-user-management
   ```
5. wait a good 5 minutes for EKS to deploy

In step 4 above, `helm-charts/charts/cht-user-management` may need be the full path to your helm charts - for me this was `/home/mrjones/Documents/MedicMobile/helm-charts/charts/cht-user-management`

**Comment by inromualdo** [comment]
Thank you @mrjones-plip 🍾
