### ISSUE TITLE
User unable to move CHA to another CHU

### ISSUE THREAD

**Issue by IreneAchola** [medic/cht-user-management#192]
There is some confusion when moving CHA(CHU?)

- It is unclear whether the process moves a CHA or a CHU, since the heading changes on selecting Community Health Unit as shown in image 2.
- In the case where the user is moving a CHA, it does not allow the user to specify the destination CHU, only the subcounty.
- The name of CHA being moved is not indicated.
- The breadcrumb is misleading. As on image 3, the before indicates `old CHU >> old subcounty`, while the after indicates `old subcounty >> new subcounty`
<img width="680" alt="Screenshot 2024-07-24 at 11 16 43" src="https://github.com/user-attachments/assets/ba4435c0-d390-4301-acad-cc128cd1d9ec">
<img width="680" alt="Screenshot 2024-07-24 at 11 25 41" src="https://github.com/user-attachments/assets/e4505018-15a8-40a9-a68a-d5472a2e9567">
<img width="680" alt="Screenshot 2024-07-24 at 11 39 53" src="https://github.com/user-attachments/assets/60c4f9d5-c02c-44cb-ab76-fb48ddcad076">

**Comment by alexosugo** [comment]
@PhilipNgari Updates have largely been pushed by individual devs targeting specific needs/deployments over the last few months. There is no specific lead on the UMT.

**Comment by billwambua** [comment]
@IreneAchola in your example it moves the CHU with the CHA contact as well of course. 

But it does not move the CHA only as the title suggests.

There is no way to move only the CHA with this tool it seems.
