### ISSUE TITLE
Resolve duplicate use of folder `dist`

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-user-management#2]
The `dist` folder is used both for the build output of typescript + for publication scripts. We should remove the `index.js` file and find a new home for the publish.js script

**Comment by mrjones-plip** [comment]
we just created a [scripts dir](https://github.com/medic/cht-user-management/tree/main/scripts/)!  be a good spot for that `publish.js`.  

and sorry for overloading  a folder name that was already in use when I prototyped this repo :(

**Comment by mrjones-plip** [comment]
Fixed in #13
