### ISSUE TITLE
Improvements to the export CSV with credentials

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-user-management#21]
Currently there is no header on the exported credentials csv file which downloads. Would be nice to have a header

**Comment by kennsippell** [comment]
> Credentials download- The current format does not contain the areas i.e 
 A CHU list output only shows the CHU name and password.This can be hard for a County based managers when distributing them to sub counties as they dont always know who to while acknowledging they can be in hundreds.
A CHP list  does not show sub counties too therefore posing the same challenge  as (a) above.
Ask- Iterate to expand  the credentials output file to be similar to  the CHP and CHA upload templates with the creds as additional columns  -Priority- High
https://docs.google.com/document/d/1-PC3GYwPPH-m7JEyqeJQmvTuTBeGivjuMDSFhhkFa3o/edit

**Comment by kennsippell** [comment]
> The progress bar load dint load for the first 2 CHPs but was visible in the last one. not very sure if I am the one who missed it and will create some more to replicate this

So the app uploads 10 users at a time. If you just made 3, then we would expect it to basically go straight from 0% to 100% in one leap.  Once you upload more than 10 users, you should see it working properly.

@freddieptf Can we add the subcounty metric? I suspect the CHA details won't be easy to add though...

**Comment by freddieptf** [comment]
Added in #83
