### ISSUE TITLE
cht-user-management-tool for west africa project

### ISSUE THREAD

**Issue by jdndiaye** [medic/cht-user-management#35]
We want to test at first the `cht-user-management-tool` on the Togo project to see how it can facilitate user management.
- Users are created centrally and regionally.
- We have 8 types of user-role
cc @kennsippell @Marina-Kenf

**Comment by kennsippell** [comment]
@jdndiaye do you have a list of all information that is expected to appear at each level in the hierarchy?

**Comment by jdndiaye** [comment]
Yes @kennsippell, we have all information for each level. Here is the [slx](https://docs.google.com/spreadsheets/d/1MDF6PfcbTSEvC-vO8thV3HR4-9H-0QIz1pJxVS3lLW4/edit#gid=1793251362).
What we don't have is a list of the locations

**Comment by Marina-Kenf** [comment]
@jdndiaye would it help to create some fake places for #moh-tog localy and try out?

Another option is #moh-mali-chw that already has places.

**Comment by jdndiaye** [comment]
Thanks @Marina-Kenf , we can do the test with Moh mali, it's even better!

**Comment by jdndiaye** [comment]
Generally on projects in West Africa:
- We may end up with 2 or more villages with the same name. Can we associate the name of the village with the name of its parent to facilitate the search?
- We have two user_role (chw and rcom) at the same level (village) cc @Marina-Kenf @kennsippell
