### ISSUE TITLE
Update Uganda configuration to match VHT creation template

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-user-management#39]
https://docs.google.com/spreadsheets/d/1g58uE5xMxFftaRIgazqk7nC1nOSGIUayQmbL-Xs4rzY/edit#gid=0

**Comment by kennsippell** [comment]
@jonathanbataire @KicaRonaldOkello 

* The credentials in 1pass for `echis.health.go.ug` are not working for me. Any ideas?
* In the template, what is the light blue color indicating? 
* Since the template specifies the parent of the VHT, do we need to indicate the district, sub-district, county, sub-county, etc.  Is this information available on the district-hospital parent?
* What happens with the `Supervisors` table in this template?  We want to create a user + contact at an existing place, but we don't want to create the place. Is that right? 
* Can you confirm that all phone numbers should require Uganda in-country numbers (eg 256 area code). [Can test library here with default County as UG](https://libphonenumber.appspot.com/)
* Can you confirm, if the VHT's name is `Jonathan Bataire` then their area would be called `Jonathan Bataire Area (village)`?

**Comment by kennsippell** [comment]
@jonathanbataire @tjovia Here is where we are at today:

![image](https://github.com/medic/cht-user-management/assets/9014751/d1dbd0c3-99ba-4402-9f42-f0f37aff9df2)
![image](https://github.com/medic/cht-user-management/assets/9014751/5408937d-9090-405d-b193-0f83ef2c0881)

### Resulting Place
```
{
  "_id": "4802fcab-7d78-4a76-8957-d1f5b90a564a",
  "_rev": "2-aeead55a9842ea04f799af1b439cce04",
  "name": "Jonathan Bataire Area (village)",
  "district": "Dist",
  "sub_district": "Subd",
  "county": "Count",
  "sub_county": "Subc",
  "parish": "Par",
  "village": "Vill",
  "type": "contact",
  "contact_type": "health_center",
  "parent": {
    "_id": "d44ba06d-4788-4576-b2a3-eeb4e7f8b862",
    "parent": {
      "_id": "app-instance-id"
    }
  },
  "user_attribution": {
    "tool": "cht_usr-1.0.6",
    "username": "medic",
    "created_time": 1706223990413
  },
  "reported_date": 1706223995945,
  "contact": {
    "_id": "3b49d6b0f1c0322c7d9ab20c29001d97",
    "parent": {
      "_id": "4802fcab-7d78-4a76-8957-d1f5b90a564a",
      "parent": {
        "_id": "d44ba06d-4788-4576-b2a3-eeb4e7f8b862",
        "parent": {
          "_id": "app-instance-id"
        }
      }
    }
  }
}
```

### Resulting Contact
```
{
  "_id": "3b49d6b0f1c0322c7d9ab20c29001d97",
  "_rev": "2-c4bdcff7fbaf50686ea61bb07c3f4373",
  "name": "Jonathan Bataire",
  "phone": "0712 344444",
  "date_of_birth": "1990 / 2 / 14",
  "sex": "Female",
  "type": "contact",
  "contact_type": "person",
  "user_attribution": {
    "tool": "cht_usr-1.0.6",
    "username": "medic",
    "created_time": 1706223990413
  },
  "reported_date": 1706223995961,
  "parent": {
    "_id": "4802fcab-7d78-4a76-8957-d1f5b90a564a",
    "parent": {
      "_id": "d44ba06d-4788-4576-b2a3-eeb4e7f8b862",
      "parent": {
        "_id": "app-instance-id"
      }
    }
  }
}
```

### Resulting User
```
{
  "_id": "org.couchdb.user:jonathan_bataire12",
  "_rev": "1-d2ac9b6b9e5e1841a0089078c0f84646",
  "name": "jonathan_bataire12",
  "type": "user",
  "roles": [
    "vht"
  ],
  "facility_id": "4802fcab-7d78-4a76-8957-d1f5b90a564a",
  "password_scheme": "pbkdf2",
  "iterations": 10,
  "derived_key": "2cfb44caf2f6b3cf55ea0f4699274c60dbb184c1",
  "salt": "c68baa5acf3186122a62cb603ff53ac0"
}
```

**Comment by jonathanbataire** [comment]
> @jonathanbataire @KicaRonaldOkello @tjovia
> 
> * The credentials in 1pass for `echis.health.go.ug` are not working for me. Any ideas?
> * In the template, what is the light blue color indicating?
> * Since the template specifies the parent of the VHT, do we need to indicate the district, sub-district, county, sub-county, etc.  Is this information available on the district-hospital parent? No worries if this needs to be specified each time, just checking.
> * What happens with the `Supervisors` table in this template?  We want to create a user + contact at an existing place, but we don't want to create the place. Is that right?
> * Can you confirm that all phone numbers should require Uganda in-country numbers (eg 256 area code). [Can test library here with default County as UG](https://libphonenumber.appspot.com/)
> * Can you confirm, if the VHT's name is `Jonathan Bataire` then their area would be called `Jonathan Bataire Area (village)`?
@kennsippell thanks for this effort
- 1password has been updated should work fine now
- Light blue is an optional input. For dob it should be able to take in age as an alternative and estimate dob back end using today's date. cos some people dont know there dobs but know there age.
- User needs to specify the, district, county, sub county, sub_district, parish and village. these are tagged on the area the parent doesnt have this information.
- For supervisor yes the place already exists we are only creating the user and contact
- I dont think we should make it madatory for all phone numbers to include country code since the app runs only in Ug. it can be confusing for some people. Currently we take numbers with or without country code. 
- yes area name should be this `Jonathan Bataire Area (village)` and should be auto generated from name and village

**Comment by jonathanbataire** [comment]
> @jonathanbataire @tjovia Here is where we are at today:
> 
> ![image](https://private-user-images.githubusercontent.com/9014751/299831364-5408937d-9090-405d-b193-0f83ef2c0881.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MTA4MTcsIm5iZiI6MTcwNjUxMDUxNywicGF0aCI6Ii85MDE0NzUxLzI5OTgzMTM2NC01NDA4OTM3ZC05MDkwLTQwNWQtYjE5My0wZjgzZWYyYzA4ODEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjlUMDY0MTU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmE3YmFkNzM2MTQ4Mjc0MmU0ZmIwNGU3NGQxZGM2ZGNhNzNmOGMzM2RmYzAzYmM5ZTc3ZmQ3ZTg4MDJhZjk5NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.UtK6n5pgDgf53D5eh4dCuhVpNBs6fC8XfuUrZNcfj90) ![image](https://private-user-images.githubusercontent.com/9014751/299829579-d1dbd0c3-99ba-4402-9f42-f0f37aff9df2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MTA4MTcsIm5iZiI6MTcwNjUxMDUxNywicGF0aCI6Ii85MDE0NzUxLzI5OTgyOTU3OS1kMWRiZDBjMy05OWJhLTQ0MDItOWY0Mi1mMGYzN2FmZjlkZjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjlUMDY0MTU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzZhOGU3NWJhN2U5MjY2YjdjMTE3ZWNiNWM2ZWYzZTliODE3OWJmODA4ODY0Mzg4NGIyYjE1M2QxYzNjNWNiZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.y6f3G1XCYE5F0FO1XHVYQa5YW_vcfGJW26fJQVIa8U0)
> 
> ### Resulting Place
> ```
> {
>   "_id": "4802fcab-7d78-4a76-8957-d1f5b90a564a",
>   "_rev": "2-aeead55a9842ea04f799af1b439cce04",
>   "name": "Jonathan Bataire Area (village)",
>   "district": "Dist",
>   "sub_district": "Subd",
>   "county": "Count",
>   "sub_county": "Subc",
>   "parish": "Par",
>   "village": "Vill",
>   "type": "contact",
>   "contact_type": "health_center",
>   "parent": {
>     "_id": "d44ba06d-4788-4576-b2a3-eeb4e7f8b862",
>     "parent": {
>       "_id": "app-instance-id"
>     }
>   },
>   "user_attribution": {
>     "tool": "cht_usr-1.0.6",
>     "username": "medic",
>     "created_time": 1706223990413
>   },
>   "reported_date": 1706223995945,
>   "contact": {
>     "_id": "3b49d6b0f1c0322c7d9ab20c29001d97",
>     "parent": {
>       "_id": "4802fcab-7d78-4a76-8957-d1f5b90a564a",
>       "parent": {
>         "_id": "d44ba06d-4788-4576-b2a3-eeb4e7f8b862",
>         "parent": {
>           "_id": "app-instance-id"
>         }
>       }
>     }
>   }
> }
> ```
> 
> ### Resulting Contact
> ```
> {
>   "_id": "3b49d6b0f1c0322c7d9ab20c29001d97",
>   "_rev": "2-c4bdcff7fbaf50686ea61bb07c3f4373",
>   "name": "Jonathan Bataire",
>   "phone": "0712 344444",
>   "date_of_birth": "1990 / 2 / 14",
>   "sex": "Female",
>   "type": "contact",
>   "contact_type": "person",
>   "user_attribution": {
>     "tool": "cht_usr-1.0.6",
>     "username": "medic",
>     "created_time": 1706223990413
>   },
>   "reported_date": 1706223995961,
>   "parent": {
>     "_id": "4802fcab-7d78-4a76-8957-d1f5b90a564a",
>     "parent": {
>       "_id": "d44ba06d-4788-4576-b2a3-eeb4e7f8b862",
>       "parent": {
>         "_id": "app-instance-id"
>       }
>     }
>   }
> }
> ```
> 
> ### Resulting User
> ```
> {
>   "_id": "org.couchdb.user:jonathan_bataire12",
>   "_rev": "1-d2ac9b6b9e5e1841a0089078c0f84646",
>   "name": "jonathan_bataire12",
>   "type": "user",
>   "roles": [
>     "vht"
>   ],
>   "facility_id": "4802fcab-7d78-4a76-8957-d1f5b90a564a",
>   "password_scheme": "pbkdf2",
>   "iterations": 10,
>   "derived_key": "2cfb44caf2f6b3cf55ea0f4699274c60dbb184c1",
>   "salt": "c68baa5acf3186122a62cb603ff53ac0"
> }
> ```

- date_of_birth should be `yyyy-mm-dd` in the contact doc
- I have a problem with "type": "contact" and "contact_type": "health_center" currently we are doing `type: health_center` same thing with person. Is this change necessary? if so queries have to change. think i've heard of `type:health_center` breaking in v4.4 for configurable hierarchies 
- since area name is generated from vht name it should come after vht name.

**Comment by jonathanbataire** [comment]
Also sex in the json should be lowercase

**Comment by kennsippell** [comment]
> Dob should support just a number of years old and infer from today's date
Will address in #41

> For supervisor yes the place already exists we are only creating the user and contact
Can there be multpile supervisors at the same place?  If a second supervisor is created at the same place, what should happen? Just create the second user? Error? Automatic replacement? Warning?

> date_of_birth should be yyyy-mm-dd in the contact doc
Done in #41

> "type": "health_center"  instead of "contact_type": "health_center"
Opened #46

> sex in the json should be lowercase
Done

> since area name is generated from vht name it should come after vht name
Currently they would both be "Jonathan Bataire".  I opened #47 but marked it as lower priority.
