### ISSUE TITLE
CHP replacement - Hide/delete all information for outgoing CHPs instead of keeping the contact

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-user-management#48]
> as the new CHP, this is very confusing. Is it possible to hide the 'name of the old CHP' from the UI using a similar approach to the way we hide names of the deceased HHs members under the Deceased Card?

> I agree with 

> 1 on @katanu response. It is better to hide the name of the old CHW.

https://github.com/moh-kenya/config-echis-2.0/issues/1858#issuecomment-1916115050

**Comment by jonathanbataire** [comment]
@kennsippell 
How are user credentials handled when replacing
for UG deployement MoH requires that no user credentials should be deleted 
so  we have a user role - "deactivated" that we assign to users we want to remove from the system the role has no permissions attached to it

**Comment by kennsippell** [comment]
@jonathanbataire Super interesting. Thanks for sharing. 
Can I ask the goal of this?

Currently, the tool does the same thing that happens when you click "delete" (this red button in CHT). 
![image](https://github.com/medic/cht-user-management/assets/9014751/8525c782-1163-434c-954f-1269039e19d1)

This does the following:
1. Deletes the `user` doc in `_users` database
2. Does not delete the `user-settings` doc in `medic` database
3. Adds `inactive: true` flag onto `user-settings` doc 

So the user isn't currently "deleted" per se.  Would this work for Uganda users?

**Comment by jonathanbataire** [comment]
> @jonathanbataire Super interesting. Thanks for sharing.
> 
> Currently, the tool does the same thing that happens when you click "delete" (this red button in CHT). ![image](https://private-user-images.githubusercontent.com/9014751/303361886-8525c782-1163-434c-954f-1269039e19d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4OTIyMDQsIm5iZiI6MTcwNzg5MTkwNCwicGF0aCI6Ii85MDE0NzUxLzMwMzM2MTg4Ni04NTI1Yzc4Mi0xMTYzLTQzNGMtOTU0Zi0xMjY5MDM5ZTE5ZDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTRUMDYyNTA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDE5YmJiMTk3MGI2YzMyZGRjYTdkOGM2M2IzNWIzYWRlYTkzNzc5ZDM4NTk5MGFlMjEyZDAwODk5NzlhMWRmYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.EdwpnoWsgPUrvn6F02fRSP4FvE2q66qmGtNjBBrxrsM)
> 
> This does the following:
> 
> 1. Deletes the `user` doc in `_users` database
> 2. Does not delete the `user-settings` doc in `medic` database
> 3. Adds `inactive: true` flag onto `user-settings` doc
> 
> So the user isn't currently "deleted" per se. Would this work for Uganda users? Can I ask the goal of the `deactivated` role?

I see  the requirement here  is to be able to restore the user's access if needed in other words reactivate the account
are we able to reactivate the account if we "delete" the doc in _users?

**Comment by kennsippell** [comment]
@jonathanbataire No, we would not be able to reactivate the account. The `_users` doc is deleted and therefore the password is lost. We would need to recreate it with a new password.
