### ISSUE TITLE
Gender form input should be a dropdown instead of freetext field 

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-user-management#55]
> Sex should be a drop down with just male and female

https://github.com/medic/cht-user-management/pull/40#issuecomment-1931829645

**Comment by inromualdo** [comment]
I propose removing this type and replacing it with a select_one type. This not only addresses the gender issue but also enables the selected items to be transformed into a dropdown. The parameter will be an object with key = select-option value and value = label.

@kennsippell

**Comment by kennsippell** [comment]
Sounds good @inromualdo!  Interested to hear which of [these tests](https://github.com/medic/cht-user-management/blob/main/test/lib/validation.spec.ts#L55-L60) will work after the change. If we break a few, I think that'd be okay. 

This may also be useful for @paulpascal to address [this feedback](https://github.com/medic/cht-user-management/pull/86#discussion_r1519206120).

**Comment by inromualdo** [comment]
It could just be `select`. I initially used `select_one`, thinking we might add `select_multiple` later. However, in the contact creation forms across several projects, I haven't seen any multiple-choice elements. So, we can simply stick with `select`.

It would look like this:
<img width="588" alt="Screenshot 2024-03-12 at 2 19 22 PM" src="https://github.com/medic/cht-user-management/assets/12269482/ab51b0ba-432e-4dbe-929a-d804c416244e">

Either options are added directly in the configs (Gender) or in a separate CSV file (Level Of Study).

<img width="376" alt="Screenshot 2024-03-12 at 2 27 54 PM" src="https://github.com/medic/cht-user-management/assets/12269482/9c02f219-3b31-4f59-9895-a331fe9a3a9f">

After the change, all gender tests will fail unless we leave the type `gender` and add the `select` type alongside it.

The genarated html will be:

<img width="440" alt="Screenshot 2024-03-12 at 2 36 16 PM" src="https://github.com/medic/cht-user-management/assets/12269482/38e31a57-3f50-4770-9b4d-54e604811d5c">

**Comment by paulpascal** [comment]
@inromualdo , we will have `select multiple` with `roles` (related #86 )

**Comment by inromualdo** [comment]
> How many levels of study are there?

This is just an example. Here, there is 5. But in the CIV project we have a select_one with more than 200 items.

> parameter already supports `array[]`

In this example, I use object, so that I can display a friendly label

> I doubt those would be easily handled by this `select_one` type

Those would be handled.
