### ISSUE TITLE
Improved performance for large table refresh - Refresh single rows instead of entire table

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-user-management#63]
After staging many users (eg. an entire county), the app exerpience slows down.  Uploads (bulk and single), refreshes, and page load (eg edit) take a long time.  Can we be more selective inwhat we are refreshing to make this experience faster?

**Comment by kennsippell** [comment]
I'm seeing 3MB requests when refreshing the table take 50s+

**Comment by freddieptf** [comment]
That should reduce significantly when we compress the html response https://github.com/medic/cht-user-management/pull/142. Did you check the timings in the developer console? I noticed fetching the HTML is not the slow part (unless you have bad internet), generating it is
