### ISSUE TITLE
Do some official design work

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-user-management#67]
Have a designer look at the current interface, give feedback, or provide a new UI design for us

**Comment by kennsippell** [comment]
Feedback shared yesterday at the "CHT User Management Planning Meeting"

> Login page UI is completely horrible

**Comment by n-orlowski** [comment]
@kennsippell is there an instance (+credentials) available to look at?

**Comment by kennsippell** [comment]
@n-orlowski For the Kenyan instance (https://users-chis-ke.app.medicmobile.org/) you can login to `Staging`. The credentials to login are under `https://chis-staging.health.go.ke/` in 1Password. Same as the credentials for the CHT instance.

There is also a Uganda instance (https://users-chis-ug.app.medicmobile.org/) which is not yet in use. The credentials to login are under `vhtapp-4x.dev.medicmobile.org` in 1password. Same as the credentials for the CHT instance.

Do you have access to these in 1password?  Note that you'll be making real users. That's fine, but probably don't go ham (1000s).

**Comment by kennsippell** [comment]
Nice! Note that [this experience](https://github.com/medic/cht-user-management/pull/56) isn't included in that version. If you want a demo of that experience, please let me know and I can set it up.

**Comment by n-orlowski** [comment]
@ZiitheH is going to be taking this on! @kennsippell, are you expecting an overall design audit including information architecture / UX or just GUI? (Our reco is the first but unsure of how much time is going into it)

**Comment by kennsippell** [comment]
You are invited, but nothing is expected.   Welcoming your thoughts and contributions. 
Mostly looking for UI/UX feedback. Don't totally know what an "information architecture audit" is.
I'd like to point out that we use [Bulma](https://bulma.io/), so it'd be nice if the UI feedback featured their controls. Material UI isn't viable with the current tech stack.

Would love us to start with a reco and talk more!

**Comment by kennsippell** [comment]
@ZiitheH Welcoming your input.  Even if you just want to start with thoughts on the login page, that might be a straightforward place for us to start our collaboration.

**Comment by ZiitheH** [comment]
Hi @kennsippell yes, I'll be sending you a doc by tomorrow! Thanks!

**Comment by ZiitheH** [comment]
Hey @kennsippell , [here](https://docs.google.com/document/d/1hsBrovnn7Nv70D8yZnC6MxatnTEz64grtSFf0YYRj8I/edit) are my initial thoughts on this. Let me know

**Comment by kennsippell** [comment]
Re-assigning to myself to split this off into GitHub issues for execution

**Comment by kennsippell** [comment]
Split this up for prioritization and execution #117 #131 #130 #129
