### ISSUE TITLE
Add monitoring via prometheus and cht-watchdog

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-user-management#68]
* Page views { by METHOD and path and status code }
* Users uploaded per instance over time
* Logins { success count, failure count, p2 failure reason }
* Count of created users { success, failure, retries, p2 time to upload }
* Alerts for outages

**Comment by mrjones-plip** [comment]
recommend that this ticket split this up into three steps/tasks:

1. expose native Prometheus end point in user man. tool - strongly suggest that no password be needed to hit Prometheus end point. This is a best practice! I believe this [article](https://stackabuse.com/nodejs-application-monitoring-with-prometheus-and-grafana/) covers publishing custom metrics from a nodejs based app. work with a generic prometheus/grafana instance to test scraping works as expected (could be local dev watchdog instance)
2.   publish new user man tool with  Prometheus end points enabled 
3. work on adding new metrics to  medic's watchdog instance and alerting on it as needed

**Comment by mrjones-plip** [comment]
For item 1 above, let's break it down for just the "Users uploaded per instance over time" metric.  Let's further assume this is an `int` that is ever incrementing.  I'd solve it like this:
1. find a way to store long lived metrics. Looking at the [compose file](https://github.com/medic/cht-user-management/blob/main/docker-compose.yml), you don't have any bind mounts and I suspect you'll need to add one so the data persists across container reboots. (as an aside, [SQLite](https://www.sqlite.org/index.html) might be a fun way to keep metrics, but it doesn't matter - it just needs to support the current and future metrics)
1. have the app read and write from the metric storage every time a user is created.  It needs to read from it to now the count.  increment in memory and then write it out to disk. you should ensure this is generic enough that other metrics can be read/written using the same code path.
1. add a new [route](https://github.com/medic/cht-user-management/tree/main/src/routes) or [service](https://github.com/medic/cht-user-management/tree/main/src/services) or what ever other code is needed to expose a new /metrics endpoint accessible via HTTP
1. ensure the new /metrics endpoint uses the correct format.  This [docs page with examples](https://prometheus.io/docs/instrumenting/exposition_formats/#text-format-example) likely has what you need.
1. add a scrape job to your local watchdog dev instance and make sure it shows up!

I'm happy to help with any of these steps!  As well, let me know if this isn't the question you were asking - I'm happy to try to answer again ;)

**Comment by ernestoteo** [comment]
@mrjones-plip  thank you.

I am exploring the options you provided above.

Is there a way to directly send these metrics to Prometheus time series database if so are there APIs we can use to send data to ?

**Comment by mrjones-plip** [comment]
@ernestoteo - Prometheus works in a pull model, not a push model.  So the target (user man tool) sets up an HTTP endpoint for anyone to use.  Then you tell Prometheus to scrape that target.  

I'd be happy to pair with you to give a demo of how this works with Watchdog.  You could then easily use the watchdog dev environment to add a new scrape target of your local user man tool that has the new HTTP endpoint.

Also wanted to note that @kennsippell suggested we not use a persistent/long lived metrics (step 1 above) and instead just keep the metrics in memory.  They'll reset every reboot of the app, which is fine for now.

**Comment by mrjones-plip** [comment]
i'm doing some prometheus related  development over in [the data ingest repo](https://github.com/medic/cht-app-monitoring-data-ingest/pull/110#issuecomment-2091926460) which might interest you @ernestoteo !
