### ISSUE TITLE
Non-admin users cannot safely find users by facility_id on > cht-core v4.4

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-user-management#76]
This tool needs to find a list of users by their `facility_id`.  To "replace" an existing user, we need to find the users which are linked to a place. Currently, we do this with [disableUsersByPlace](https://github.com/medic/cht-user-management/blob/main/src/lib/cht-api.ts#L141) but this isn't working for non-admin users.

Three issues combine to make this issue quick sticky:
* Non-admin users (users with `mm-online` role) get a 403 unauthorized when running the `_users/_find` query currently in use.  Access to the `_users` database is for admins only after CHT 4.4's upgrade of CouchDB.
* The `GET /api/v2/users` API endpoint doesn't support looking up users by facility_id https://github.com/medic/cht-core/issues/8877
* It isn't safe to run `/api/v2/users` to fetch all users and filter it in memory by facility_id https://github.com/medic/cht-core/issues/8689

This blocks "replace user" scenarios for devolved user management. cc @freddieptf

**Comment by kennsippell** [comment]
Options?

1. Upgrade to 4.6
2. Backport fix for https://github.com/medic/cht-core/issues/8689 back to 4.2.x and upgrade
3. Modify `_users/_security` doc to permit access to the `user_manager` role

This only affects CHT-Core 4.4 or later. So we have a bit of time for this since eCHIS is on 4.2 and 4.3.

**Comment by mrjones-plip** [comment]
> This could potentially block CHIS upgrades

thanks for the heads up!  Let's see if the [work around proposed](https://github.com/medic/cht-core/issues/8877#issuecomment-1948531882) in the ticket is viable and go from there. 

I'll be keeping an eye out for updates!

**Comment by mrjones-plip** [comment]
Great to see the ddoc work around is deployed!

Note that  https://github.com/medic/cht-core/issues/8877 is under way and will be released in CHT `4.7.0`

**Comment by kennsippell** [comment]
Reactivating due to https://github.com/medic/cht-user-management/issues/115

**Comment by mrjones-plip** [comment]
@kennsippell - are you able to reproduce this in a dev environment?  I wonder if using the [new users API](https://github.com/medic/cht-core/issues/8877) going to be released in 4.7 would be a solution?  If you can reproduce it in a dev environment, then we could try using the [branch images](https://github.com/medic/cht-core/pull/8928) on `8877-lookup-single-user` to see if the new API fixes the timeout.  

I know that the new API PR isn't final and there were maybe some performance concerns, but the build is green, so the images have published!

 cc @jkuester @m5r

**Comment by kennsippell** [comment]
@mrjones-plip Yep. We will try it out. https://github.com/medic/cht-user-management/issues/114
Means cht-user-management wont work with cht-core 4.4 to 4.6.

**Comment by m5r** [comment]
The two users APIs `GET /api/v2/users/:username` and `GET /api/v2/users?{facility_id,contact_id}=` have been merged to cht-core master and will be part of the 4.7.0 release

https://github.com/medic/cht-core/pull/9016
https://github.com/medic/cht-core/pull/8928

And their documentation is already out:
https://docs.communityhealthtoolkit.org/apps/reference/api/#get-apiv2users
https://docs.communityhealthtoolkit.org/apps/reference/api/#get-apiv2usersusername

**Comment by kennsippell** [comment]
@m5r That's great! Thanks.

There are 4 eCHIS Kenya instances running cht-core 4.4 or 4.5.  I don't know how that happened, but I can't downgrade them to 4.3.1 to get them working with cht-user-management.  

If we backport your changes to 4.6.x, then I will push to upgrade all eCHIS instances to 4.6.x instead of 4.3.1 in [these tickets](https://medic.slack.com/archives/C042D6TPC3Y/p1713151739049359) https://github.com/moh-kenya/config-echis-2.0/issues/2096.
