### ISSUE TITLE
Create KE user manager accounts

### ISSUE THREAD

**Issue by kennsippell** [medic/cht-user-management#79]
Scripts to create the `user_manager` accounts for https://github.com/moh-kenya/config-echis-2.0/issues/1908

**Comment by kennsippell** [comment]
The following domains are not in 1password and so I cannot create accounts for these instances:

- bungoma.echis.go.ke
- busia.echis.go.ke
- elgeyomarakwet.echis.go.ke
- kajiado.echis.go.ke
- kirinyaga.echis.go.ke
- laikipia.echis.go.ke
- lamu.echis.go.ke
- mandera.echis.go.ke
- marsabit.echis.go.ke
- meru.echis.go.ke
- mombasa.echis.go.ke
- muranga.echis.go.ke
- narok.echis.go.ke
- nyamira.echis.go.ke
- nyandarua.echis.go.ke
- transnzoia.echis.go.ke
- wajir.echis.go.ke

cc @PhilipNgari @alexosugo

**Comment by alexosugo** [comment]
@kennsippell The checked credentials have been added to 1Password. I'll keep updating them as I get more passwords.

**Comment by kennsippell** [comment]
Status update

The above 9 sub-counties are still blocked due to missing credentials in 1pass
- [ ] bungoma.echis.go.ke
- [ ] busia.echis.go.ke
- [ ] mandera.echis.go.ke
- [ ] marsabit.echis.go.ke
- [ ] meru.echis.go.ke
- [ ] muranga.echis.go.ke
- [ ] narok.echis.go.ke
- [ ] nyamira.echis.go.ke
- [ ] wajir.echis.go.ke

These are blocked by the fact that there is not yet any county information on the instance:
- [ ] kisumu
- [ ] garissa
- [ ] tanariver

These are blocked by login problems #102 
- [ ] isiolo
- [ ] siaya
- [ ] chs-training

These training instances are blocked by #106 
- [ ] chis-training
- [ ] chis-training-2
- [ ] chis-training-3

**Comment by alexosugo** [comment]
@kennsippell I updated 1Password this morning with 4 of the 9 missing credentials.

**Comment by kennsippell** [comment]
Credentials sent to 12 active user managers today. Shared 1password link via email.

**Comment by kennsippell** [comment]
Marsabit, Nyamira, Garissa, Tana River, Kisumu complete.
Training + Siaya still blocked.
Mandera, Narok, Wajir still not in 1password cc @alexosugo.

**Comment by alexosugo** [comment]
@kennsippell Narok is available on 1Password. Mandera and Wajir instances are not yet live.

**Comment by kennsippell** [comment]
@alexosugo The password for Narok doesn't seem to work.  Also the eCHIS config doesn't appear to be deployed on that instance (?)

**Comment by alexosugo** [comment]
@kennsippell Narok Couchdb was unreachable hence the login issue. It's now back up and accessible with the same credentials. eCHIS config is present too.
